version: '3.1'

services:
  #  app:
  #    build:
  #      context: ../
  #      dockerfile: "deployment/docker/Dockerfile"
  #    volumes:
  #      - ../:/app
  #    environment:
  #      POSTGRES_URI: ${POSTGRES_URI}
  #    ports:
  #      - ${APP_PORT}:8000
  #    depends_on:
  #      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  #  test_runner:
  #    build:
  #      context: ../
  #      dockerfile: "deployment/docker/test-runner.Dockerfile"
  #    volumes:
  #      - ../:/app
  #    command: ["go", "test", "./..."]
  #    depends_on:
  #      - postgres_test

  postgres_test:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
